In [1]:
import pandas as pd
df=pd.read_csv(r"D:\VS_CODE\Traffic_violations\Traffic_Violations.csv")
df.head()

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,...,Charge,Article,Contributed To Accident,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation
0,52282e8c-f2e1-4bb5-8509-2d5e4f8da8ca,05/01/2023,23:11:00,MCP,"3rd District, Silver Spring",OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.000000,0.00000,No,...,13-401(b1),Transportation Article,False,WHITE,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(0.0, 0.0)"
1,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.15301,No,...,16-101(a1),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"
2,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.15301,No,...,13-409(b),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"
3,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.15301,No,...,21-310(a),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"
4,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.15301,No,...,21-801(b),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"

In [5]:
#Check the shape of the dataframe
df.shape

(2070115, 43)

In [6]:
#Display the columns list
df.columns

Index(['SeqID', 'Date Of Stop', 'Time Of Stop', 'Agency', 'SubAgency',
       'Description', 'Location', 'Latitude', 'Longitude', 'Accident', 'Belts',
       'Personal Injury', 'Property Damage', 'Fatal', 'Commercial License',
       'HAZMAT', 'Commercial Vehicle', 'Alcohol', 'Work Zone',
       'Search Conducted', 'Search Disposition', 'Search Outcome',
       'Search Reason', 'Search Reason For Stop', 'Search Type',
       'Search Arrest Reason', 'State', 'VehicleType', 'Year', 'Make', 'Model',
       'Color', 'Violation Type', 'Charge', 'Article',
       'Contributed To Accident', 'Race', 'Gender', 'Driver City',
       'Driver State', 'DL State', 'Arrest Type', 'Geolocation'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2070115 entries, 0 to 2070114
Data columns (total 43 columns):
 #   Column                   Dtype
---  ------                   -----
 0   SeqID                    object
 1   Date Of Stop             object
 2   Time Of Stop             object
 3   Agency                   object
 4   SubAgency                object
 5   Description              object
 6   Location                 object
 7   Latitude                 float64
 8   Longitude                float64
 9   Accident                 object
 10  Belts                    object
 11  Personal Injury          object
 12  Property Damage          object
 13  Fatal                    object
 14  Commercial License       object
 15  HAZMAT                   object
 16  Commercial Vehicle       object
 17  Alcohol                  object
 18  Work Zone                object
 19  Search Conducted         object
 20  Search Disposition       object
 21  Search Outcome           object
 22  Search Reason            object
 23  Search Reason For Stop   object
 24  Search Type              object
 25  Search Arrest Reason     object
 26  State                    object
 27  VehicleType              object
 28  Year                     float64
 29  Make                     object
 30  Model                    object
 31  Color                    object
 32  Violation Type           object
 33  Charge                   object
 34  Article                  object
 35  Contributed To Accident  bool
 36  Race                     object
 37  Gender                   object
 38  Driver City              object
 39  Driver State             object
 40  DL State                 object
 41  Arrest Type              object
 42  Geolocation              object
dtypes: bool(1), float64(3), object(39)
memory usage: 665.3+ MB

In [8]:
#Check if there are duplicates
df.duplicated().sum()

np.int64(2354)

In [9]:
#Drop the duplicates
df.drop_duplicates(inplace=True)

In [10]:
#Check if there are duplicates again
df.duplicated().sum()

np.int64(0)

                  DATA CLEANING AND PREPROCESSSING

                         SeqID

In [11]:
#Change the datatype of the columns SeqID  from object to string
df['SeqID']=df['SeqID'].astype("string")

In [12]:
#Display hte datatype of the column
df['SeqID'].dtype

string[python]

                                 Date Of Stop

In [13]:
df["Date Of Stop"].dtype

dtype('O')

In [14]:
#Check for dash and slash in the data column
dash_mask=df["Date Of Stop"].str.contains("-")
slash_mask=df["Date Of Stop"].str.contains("/")

In [15]:
#Change the data type based on mask
import numpy as np
df["Date Of Stop"]=np.where(dash_mask,pd.to_datetime(df["Date Of Stop"],dayfirst=True,errors="coerce"),pd.to_datetime(df["Date Of Stop"],dayfirst=False,errors="coerce"))

In [16]:
#Now the date of stop column is changed to the std date format yyyy-mm-dd
df["Date Of Stop"].head()

0   2023-05-01
1   2023-08-31
2   2023-08-31
3   2023-08-31
4   2023-08-31
Name: Date Of Stop, dtype: datetime64[ns]

In [17]:
#Now check the date of stop
df["Date Of Stop"].dtype

dtype('<M8[ns]')

In [18]:
#Handling the future and inconsistent dates
today=pd.Timestamp.today()
df.loc[df["Date Of Stop"]>today,"Date Of Stop"]=pd.NaT
df.loc[df["Date Of Stop"].dt.year>today.year,"Date Of Stop"]=pd.NaT

                                                TIME OF STOP

In [19]:
#Change the format of Time of stop column to standard format
df["Time Of Stop"]=df["Time Of Stop"].str.replace(".",":",regex=False)
df["Time Of Stop"]=pd.to_datetime(df["Time Of Stop"],format="%H:%M:%S",errors="coerce").dt.time

                                    #Combine the date and time columns to a new column

In [20]:
df["stop_timestamp"]=pd.to_datetime(df["Date Of Stop"].astype(str) + "  "+ df["Time Of Stop"].astype(str),errors="coerce")

In [21]:
#Display the new column
df["stop_timestamp"].head()

0   2023-05-01 23:11:00
1   2023-08-31 16:41:00
2   2023-08-31 16:41:00
3   2023-08-31 16:41:00
4   2023-08-31 16:41:00
Name: stop_timestamp, dtype: datetime64[ns]

                                            AGENCY

In [22]:
#Change the case to uppercase and remove the spaces at both the ends

df["Agency"]=df["Agency"].str.upper().str.strip()

In [23]:
#Check the unique values in the column Agency
df["Agency"].unique()

array(['MCP'], dtype=object)

                                                    SUB AGENCY

In [24]:
#Standardize spacing & punctuation
df["SubAgency"]=df["SubAgency"].str.strip().str.replace(r"\s+"," ",regex=True)
df["SubAgency"]=df["SubAgency"].str.replace(" ,", ",", regex=False)

In [25]:
#Convert to a consistent case
df["SubAgency"] = df["SubAgency"].str.title()

In [26]:
#Standardize the suffix of the district number
df["SubAgency"] = df["SubAgency"].str.replace(
    r"(\d+)(Th|St|Nd|Rd)", 
    lambda x: x.group(0).lower(), 
    regex=True
)

In [27]:
#Display the Sub agency column
df["SubAgency"].head()

0                        3rd District, Silver Spring
1    6th District, Gaithersburg / Montgomery Village
2    6th District, Gaithersburg / Montgomery Village
3    6th District, Gaithersburg / Montgomery Village
4    6th District, Gaithersburg / Montgomery Village
Name: SubAgency, dtype: object

In [28]:
#Extract the district number
def extract_district_number(text):
    import re
    temp=re.findall(r"(\d+)(?:th|st|nd|rd)?\s+District",text)
    return temp[0] if temp else None
df["District_number"] = df["SubAgency"].apply(extract_district_number)

                                          Description

In [29]:
# Creating a new column Violation_Category from the  original column "Description"

def categorize(desc: str) -> str:
    desc = str(desc).lower()
    if "speed" in desc:
        return "Speeding"
    elif "registration" in desc:
        return "Registration"
    elif "license" in desc:
        return "License"
    elif "insurance" in desc:
        return "Insurance"
    elif "seatbelt" in desc:
        return "Seatbelt"
    elif "alcohol" in desc:
        return "Alcohol"
    elif "unregistered" in desc:
        return "Unregistered"
    else:
        return "Other"

# ✅ Add new column to your existing df
df["Violation_Category"] = df["Description"].apply(categorize)

# Optional: make it efficient
df["Violation_Category"] = df["Violation_Category"].astype("category")

print(df.head())
print(df.dtypes)

                                  SeqID Date Of Stop Time Of Stop Agency  \
0  52282e8c-f2e1-4bb5-8509-2d5e4f8da8ca   2023-05-01     23:11:00    MCP
1  b66f253b-af29-4bc4-bb73-93755ca2a779   2023-08-31     16:41:00    MCP
2  b66f253b-af29-4bc4-bb73-93755ca2a779   2023-08-31     16:41:00    MCP
3  b66f253b-af29-4bc4-bb73-93755ca2a779   2023-08-31     16:41:00    MCP
4  b66f253b-af29-4bc4-bb73-93755ca2a779   2023-08-31     16:41:00    MCP

                                         SubAgency  \
0                      3rd District, Silver Spring
1  6th District, Gaithersburg / Montgomery Village
2  6th District, Gaithersburg / Montgomery Village
3  6th District, Gaithersburg / Montgomery Village
4  6th District, Gaithersburg / Montgomery Village

                                         Description  \
0    OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY
1  DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...
2  FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...
3  DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...
4  FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...

                           Location   Latitude  Longitude Accident  ...  \
0  BRIGGS CHANEY RD @ COLUMIBA PIKE   0.000000    0.00000       No  ...
1       OAKMONT AVE @ GROVEMONT CIR  39.097965  -77.15301       No  ...
2       OAKMONT AVE @ GROVEMONT CIR  39.097965  -77.15301       No  ...
3       OAKMONT AVE @ GROVEMONT CIR  39.097965  -77.15301       No  ...
4       OAKMONT AVE @ GROVEMONT CIR  39.097965  -77.15301       No  ...

       Race Gender   Driver City Driver State DL State        Arrest Type  \
0     WHITE      M  GAITHERSBURG           MD       MD  A - Marked Patrol
1  HISPANIC      M  GAITHERSBURG           MD       MD  A - Marked Patrol
2  HISPANIC      M  GAITHERSBURG           MD       MD  A - Marked Patrol
3  HISPANIC      M  GAITHERSBURG           MD       MD  A - Marked Patrol
4  HISPANIC      M  GAITHERSBURG           MD       MD  A - Marked Patrol

              Geolocation      stop_timestamp District_number  \
0              (0.0, 0.0) 2023-05-01 23:11:00               3
1  (39.097965, -77.15301) 2023-08-31 16:41:00               6
2  (39.097965, -77.15301) 2023-08-31 16:41:00               6
3  (39.097965, -77.15301) 2023-08-31 16:41:00               6
4  (39.097965, -77.15301) 2023-08-31 16:41:00               6

  Violation_Category
0       Unregistered
1            License
2       Registration
3              Other
4           Speeding

[5 rows x 46 columns]
SeqID                      string[python]
Date Of Stop               datetime64[ns]
Time Of Stop                       object
Agency                             object
SubAgency                          object
Description                        object
Location                           object
Latitude                          float64
Longitude                         float64
Accident                           object
Belts                              object
Personal Injury                    object
Property Damage                    object
Fatal                              object
Commercial License                 object
HAZMAT                             object
Commercial Vehicle                 object
Alcohol                            object
Work Zone                          object
Search Conducted                   object
Search Disposition                 object
Search Outcome                     object
Search Reason                      object
Search Reason For Stop             object
Search Type                        object
Search Arrest Reason               object
State                              object
VehicleType                        object
Year                              float64
Make                               object
Model                              object
Color                              object
Violation Type                     object
Charge                             object
Article                            object
Contributed To Accident              bool
Race                               object
Gender                             object
Driver City                        object
Driver State                       object
DL State                           object
Arrest Type                        object
Geolocation                        object
stop_timestamp             datetime64[ns]
District_number                    object
Violation_Category               category
dtype: object

                                                      LOCATION

In [30]:
#Standardize @ or / separators and make it as &
df["Location_clean"] = (
    df["Location"]
    .str.replace("@", " & ", regex=False)
    .str.replace("/", " & ", regex=False)
    .str.replace("At", " & ", regex=False)
    .str.replace(r"\s+", " ", regex=True)   # remove double spaces
    .str.strip()
)

In [31]:
# Split on '&' and flatten
df["Roads"] = df["Location_clean"].str.split("&")
df["Roads"]

0             [BRIGGS CHANEY RD ,  COLUMIBA PIKE]
1                  [OAKMONT AVE ,  GROVEMONT CIR]
2                  [OAKMONT AVE ,  GROVEMONT CIR]
3                  [OAKMONT AVE ,  GROVEMONT CIR]
4                  [OAKMONT AVE ,  GROVEMONT CIR]
                            ...
2070110                 [RAMSEY AVE ,  WAYNE AVE]
2070111               [GEORGIA AVE ,  ARCOLA AVE]
2070112    [E RANDOLPH ROAD ,  OLD COLUMBIA PIKE]
2070113          [GAINSBOROUGH RD ,  HOB NAIL CT]
2070114         [WOODFIELD DR ,  FLOWER HILL WAY]
Name: Roads, Length: 2067761, dtype: object

In [32]:
# Handle casing
df["Location_clean"] = df["Location_clean"].str.title()
df["Location_clean"]

0             Briggs Chaney Rd & Columiba Pike
1                  Oakmont Ave & Grovemont Cir
2                  Oakmont Ave & Grovemont Cir
3                  Oakmont Ave & Grovemont Cir
4                  Oakmont Ave & Grovemont Cir
                          ...
2070110                 Ramsey Ave & Wayne Ave
2070111               Georgia Ave & Arcola Ave
2070112    E Randolph Road & Old Columbia Pike
2070113          Gainsborough Rd & Hob Nail Ct
2070114         Woodfield Dr & Flower Hill Way
Name: Location_clean, Length: 2067761, dtype: object

In [33]:
import numpy as np
# Convert Latitude to numeric
df["Latitude"]=pd.to_numeric(df["Latitude"],errors="coerce")

 #Replace 0 with NaN
df.loc[df["Latitude"]==0,"Latitude"]=np.nan

#Remove impossible coordinates
#- Global latitude range: - –90° (South Pole) and +90° (North Pole).
#- U.S. latitude range:  - 24°N (southern Florida) and 49°N (northern border with Canada).

df.loc[(df["Latitude"] < 24) | (df["Latitude"] > 49), "Latitude"] = np.nan
df["Latitude"].describe()

count    1.912005e+06
mean     3.908538e+01
std      7.083641e-02
min      3.504941e+01
25%      3.903303e+01
50%      3.907487e+01
75%      3.914478e+01
max      4.154316e+01
Name: Latitude, dtype: float64

                                                    LONGITUDE

In [34]:
#. Convert Longitude to numeric
df["Longitude"] = pd.to_numeric(df["Longitude"], errors="coerce")

#Replace 0 with NaN
df.loc[df["Longitude"] == 0, "Longitude"] = np.nan

# Validate ranges
#- Global valid range: –180 to +180 (longitude wraps around the globe).
#- U.S. practical range: about –125 (West Coast) to –65 (East Coast).
df.loc[(df["Longitude"] < -125) | (df["Longitude"] > -65), "Longitude"] = np.nan
df["Longitude"].describe()

count    1.912007e+06
mean    -7.711667e+01
std      1.459426e-01
min     -1.203847e+02
25%     -7.720103e+01
50%     -7.709804e+01
75%     -7.704663e+01
max     -7.128571e+01
Name: Longitude, dtype: float64

#10–18. Boolean Columns (Accident, Belts, Personal Injury, Property Damage, Fatal, Commercial License, HAZMAT, Commercial Vehicle, Alcohol)

In [35]:
#standardize them all to lowercase first:
for col in ["Accident","Belts","Personal Injury","Property Damage",
            "Fatal","Commercial License","HAZMAT","Commercial Vehicle","Alcohol"]:
    df[col] = df[col].astype(str).str.strip().str.lower()


#Map to True/False
map_bool = {
    "yes": True, "y": True, "true": True, "t": True, "1": True,
    "no": False, "n": False, "false": False, "f": False, "0": False, "": False, "nan": False
}

for col in ["Accident","Belts","Personal Injury","Property Damage",
            "Fatal","Commercial License","HAZMAT","Commercial Vehicle","Alcohol"]:
    df[col] = df[col].map(map_bool)


df[["Accident","Belts","Personal Injury","Property Damage",
            "Fatal","Commercial License","HAZMAT","Commercial Vehicle","Alcohol"]]

,Accident,Belts,Personal Injury,Property Damage,Fatal,Commercial License,HAZMAT,Commercial Vehicle,Alcohol
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2070110,False,False,False,False,False,False,False,False,False
2070111,False,False,False,False,False,False,False,False,False
2070112,False,False,False,False,False,False,False,False,False
2070113,False,False,False,False,False,False,False,False,False
2070114,False,False,False,False,False,False,False,False,False

                                                    #WORK ZONE

In [36]:
# Normalize to lowercase strings
df["Work Zone"] = df["Work Zone"].astype(str).str.strip().str.lower()

# Define mapping
map_bool = {
    "yes": True, "y": True, "true": True, "t": True, "1": True,
    "no": False, "n": False, "false": False, "f": False, "0": False,
    "": False, "nan": False
}

# Apply mapping
df["Work Zone"] = df["Work Zone"].map(map_bool)
df["Work Zone"].head()

0    False
1    False
2    False
3    False
4    False
Name: Work Zone, dtype: bool

                                                      Search Conducted

In [37]:
# Normalize to lowercase strings
df["Search Conducted"] = df["Search Conducted"].astype(str).str.strip().str.lower()

# Define mapping
map_bool = {
    "yes": True, "y": True, "true": True, "t": True, "1": True,
    "no": False, "n": False, "false": False, "f": False, "0": False,
    "": False, "nan": False   # blanks and NaN treated as No
}

# Apply mapping
df["Search Conducted"] = df["Search Conducted"].map(map_bool)
df["Search Conducted"].head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Search Conducted, dtype: bool

                                             Search Disposition

In [38]:
df["Search Disposition"].unique()

array([nan, 'Nothing', 'Contraband Only', 'Property Only',
       'Contraband and Property', 'DUI', 'nothing', 'marijuana'],
      dtype=object)

In [39]:
import pandas as pd

# Example: assume df["Search Outcome"] exists

# Step 1: Normalize casing and strip spaces
df["Search Disposition"] = df["Search Disposition"].astype(str).str.strip().str.title()

# Step 2: Define mapping dictionary
map_outcome = {
    "Nothing": "Nothing Found",
    "Contraband Only": "Contraband",
    "Property Only": "Property",
    "Contraband And Property": "Contraband + Property",
    "Dui": "DUI Evidence",
    
}

# Step 3: Apply mapping
df["Search Disposition"]= df["Search Disposition"].replace(map_outcome)

# Step 4: KPI counts
Disposition_counts = df["Search Disposition"].value_counts(dropna=False)

print(Disposition_counts)

Search Disposition
Nan                      1978521
Nothing Found              38777
Contraband                 22787
Property                   14742
Contraband + Property      12918
DUI Evidence                  12
Marijuana                      4
Name: count, dtype: int64

                                                     Search Outcome

In [40]:
df['Search Outcome'].value_counts()

Search Outcome
Warning               638394
Citation              525567
Arrest                 62574
SERO                   36662
Recovered Evidence         3
Name: count, dtype: int64

In [41]:
#- Normalize casing and strip spaces
df["Search Outcome"] = df["Search Outcome"].astype(str).str.strip().str.title()

In [42]:
#Standardize categories with a mapping dictionary
map_outcome = {
    "Warning": "Warning Given",
    "Citation": "Citation Issued",
    "Arrest": "Arrest Made",
    "Sero": "SERO Issued",
    "Recovered Evidence": "Evidence Recovered",
}

df["Search Outcome"] = df["Search Outcome"].replace(map_outcome)

                                                  Search Reason

In [43]:
#Unique values in the column
df['Search Reason'].value_counts()

Search Reason
Incident to Arrest        51586
Probable Cause            21617
Consensual                12399
K-9                        1973
Other                      1116
Exigent Circumstances       537
Probable Cause for CDS        5
Arrest/Tow                    3
plain view marijuana          3
DUI                           1
Name: count, dtype: int64

In [44]:


# Normalize casing and strip spaces
df["Search Reason"] = df["Search Reason"].astype(str).str.strip().str.title()

# Define mapping dictionary for recruiter‑friendly labels
map_reason = {
    "Incident To Arrest": "Incident to Arrest",
    "Probable Cause": "Probable Cause",
    "Consensual": "Consensual Search",
    "K-9": "K-9 Search",
    "Other": "Other Reason",
    "Exigent Circumstances": "Exigent Circumstances",
    "Probable Cause For Cds": "Probable Cause for CDS",
    "Arrest/Tow": "Arrest or Tow",
    "Plain View Marijuana": "Plain View (Marijuana)",
    "Dui": "DUI Evidence",
}

# Apply mapping safely
df["Search Reason"] = df["Search Reason"].replace(map_reason)

In [45]:
#Unique values in the column
df['Search Reason'].value_counts()

Search Reason
Nan                       1978521
Incident to Arrest          51586
Probable Cause              21617
Consensual Search           12399
K-9 Search                   1973
Other Reason                 1116
Exigent Circumstances         537
Probable Cause for CDS          5
Arrest or Tow                   3
Plain View (Marijuana)          3
DUI Evidence                    1
Name: count, dtype: int64

                                                    Search Reason For Stop

In [46]:
##Unique values in the column
df['Search Reason For Stop'].value_counts()

Search Reason For Stop
21-201(a1)      154258
21-801.1         98194
13-411(f)        68610
21-707(a)        60210
13-401(h)        52499
                 ...
22-210(d)            1
11-395.15(g)         1
22-222(a2)           1
21-901.2(A)          1
21-510(a)            1
Name: count, Length: 842, dtype: int64

In [47]:
df['Search Reason For Stop'].nunique()

842

In [48]:
#Check for null values
df['Search Reason For Stop'].isnull().sum()

np.int64(785598)

In [49]:
#Normalize the column like removing trailing spaces,changing to upper case
def clean_code(code):
    if code is None:
        return None
    return str(code).strip().upper()
df['Search Reason For Stop']= df['Search Reason For Stop'].apply(clean_code)

In [50]:
df['Search Reason For Stop'].unique()

array(['17-107(A1)', '20-102(A1)', '55*', 'NAN', '13-401(H)', '21-304(C)',
       '13-411(G)', '21-202(H2)', '21-204(B)', '22-412.2(D1)', '21-801.1',
       '21-901.1(A)', '21-201(A1)', '21-202(H1)', '21-402(A)',
       '13-411(F)', '21-801(A)', '16-305(A)', '21-1003(E)', '21-1001(B)',
       '13-703(G)', '21-707(A)', '13-411(D)', '61', '20-105(A)',
       '21-405(E2I)', '13-401(B1)', '21-601(A)', '21-204(D)', '16-116(A)',
       '21-1102(A)', '22-203(B)', '16-101(A1)', '16-112(C)', '21-1117(D)',
       '21-902(A1I)', '21-1124.2(D2)', '21-309(B)', '21-1003(AA)',
       '21-801(B)', '21-904(B1)', '21-301(A)', '13-409(B)',
       '21-1124.1(B)', '64*', '21-201(A2)', '21-305', '21-1103(A)',
       '22-201.1', '22-219(E)', '21-202(C)', '21-202(M)', '11-391.41(A)',
       '65*', '21-309(D)', '13-411(A)', '22-209(B)', '22-406(I1)',
       '22-216', '24-106(C)', '13-411(C1I)', '13-410(E2)', '21-706(A)',
       '22-219(A)', '21-403(B)', '23-104', '22-204(F)', '21-309(I)',
       '22-209(A)', '21-1003(D)', '22-226(A)', '22-204(A)', '56*', '81',
       '16-105(B1)', '21-901.1(B)', '22-412.3(B)', '16-303(C)',
       '22-412.3(C2)', '21-304(B)', '17-107(A2)', '21-1112.1(A)',
       '22-210(C)', '21-502(A2)', '21-202(I1)', '21-401', '21-705(C)',
       '21-1001(A)', '21-309(E)', '21-405(B)', '22-227(D)',
       '21-902(A1II)', '11-390.21', '21-601(B)', '21-502(B)',
       '13-411(C1II)', '22-101(A)', '22-609(A)', '21-1306.1(B)',
       '13-411(E)', '13-701(A)', '16-305(B)', '87*', '13-936E2I',
       '21-404(A)', '11-393.9', '21-1003(Q)', '21-601(C)', '22-204(B)',
       '21-1408(A)', '21-1003(G)', '21-307(B)', '21-602(A)', '16-303(F)',
       '21-604(A)', '61*', '21-1124.2(C1)', '53', '21-314(B)',
       '21-707(B)', '11-392.82', '11-393.41', '21-403(C)', '22-206(A1I)',
       '22-206A(1II)', '21-505', '21-604(D)', '21-1003(J)', '20-103(B)',
       '21-804(A)', '21-1125(1)', '22-402(B)', '21-604(C)', '21-103(A)',
       '22-609(B)', '10-319.1', '21-1116(A)', '22-214(B)', '21-902(B1I)',
       '22-208', '22-206A1(III)', '13-411C(1II)', '22-227(B)',
       '21-601(D)', '21-310(A)', '21-1129', '22-204(D)', '21-1003(R)',
       '21-309(C)', '16-115(G)', '21-1117(C)', '21-202(E)', '21-203(C)',
       '50', '21-309(H)', '21-1303(D)', '21-1303.1(A)', '21-1003(U)',
       '21-308(A)', '21-503(C)', '22-406(D)', '22-201.2', '11-393.10(0B)',
       '21-706(B)', '16-113(K)', '21-1003(O)', '21-303(B)', '21-1303(C)',
       '21-202(I2)', '21-1133(A)', '21-602(B)', '21-405E(2II)',
       '21-502(C)', '11-392.9B(A)', '22-219(G)', '21-405(C)', '21-311(1)',
       '20-103(A)', '21-404(B)', '21-307(C)', '21-604(B)', '22-211(C)',
       '21-902(C1I)', '13-401(J)', '21-603(A)', '21-1101(A)', '14-110(B)',
       '21-1104(C3)', '21-902(A1)', '22-406(I3)', '22-404(A1)',
       '21-1003(C)', '13-106(D2)', '16-101(B)', '14-110(G)', '21-903(C)',
       '21-1003(B)', '13-411(B2)', '21-1404(A)', '21-1005(M)',
       '21-404.1(A)', '21-1111(D)', '21-202(K)', '25-202(A1)',
       '21-1104(C1)', '22-223(B)', '59', '21-301(B1)', '22-211(B)',
       '13-616.1(F1)', '21-1003(L)', '21-901.2', '88*', '21-605(A)',
       '16-303(D)', '22-206(A)', '13-604(C)', '21-307(D1)', '22-215.1(2)',
       '21-1116.1(B)', '21-1124.2(C2)', '11-393.43', '21-1104(D)',
       '20-108', '21-1306(B)', '89', '13-411(C1)', '21-402(B)',
       '13-402(A2)', '22-223(C)', '11-392.2', '21-605(C)', '21-405(D)',
       '21-705(A)', '21-202(J)', '17-104.2(B2)', '22-227(C)', '21-508',
       '22-401(B)', '21-403(D)', '22-301(F)', '14-105(C)', '16-303(H)',
       '21-1203(C)', '13-415(G)', '21-503(D)', '21-803.1(E)',
       '21-405E(2I)', '20-105(B)', '22-218(E)', '21-405(A)',
       '21-404.1(B)', '21-1110', '22-406(B)', '21-209(2)', '21-2091(II)',
       '21-1306.1(C)', '22-230(B)', '21-804(B)', '21-204(C)',
       '21-405(E2)', '22-405.2(B)', '14-108(A)', '21-309(G)', '21-504(A)',
       '11-393.75(C)', '11-393.95(F)', '11-393.78', '80*', '21-801(E)',
       '13-411(H)', '22-222(C)', '22-405(A)', '14-104(A)', '22-412.3(C3)',
       '13-415(F)', '21-301(C)', '13-920(G)', '22-205(A)', '21-1120(C)',
       '22-218(C)', '21-2091(I)', '21-1003(S)', '21-1122(C)', '7-705(F1)',
       '21-1404(D)', '24-106.1(D2)', '11-392.14', '21-1003(M)',
       '21-1003(DD)', '21-503(A)', '13-415(A)', '20-105.1', '20-102(A2)',
       '21-1006(B)', '21-605(B)', '22-403(B)', '22-206(C)',
       '11-393.95(A)', '13-411(C2)', '24-106.1(F)', '14-102(B)',
       '13-605(C)', '22-206(A1)', '21-705(B)', '16-301(E)',
       '17-104.2(B1)', '11-391.11(A)', '23-109(I)', '21-1102(B)',
       '22-404(C)', '22-221(F)', '21-902(A2I)', '21-1003(N)', '16-113(I)',
       '11-393.48', '22-218(B)', '22-203(C1)', '21-1408(B)', '22-227(A)',
       '16-101(A)', '21-1407', '21-311(2)', '21-506(A)', '22-401(C)',
       '11-392.16', '21-902(D1I)', '21-801(H)', '16-104.1(C)',
       '11-393.11(0A)', '21-1109(A)', '13-415(H)', '13-616.1(F2)',
       '13-402.1(E2)', '21-1302(D)', '22-222(A)', '21-1203(B)',
       '13-606(C)', '24-106.1(E2)', '60*', '21-1116(A1)', '11-396.7',
       '21-1004.1(A)', '22-301(B)', '16-113(H)', '13-402(A1)',
       '22-222(A4)', '22-227(E)', '21-509(B)', '13-616.2(E2)',
       '22-101(B3)', '11-393.47(E)', '22-214(A)', '21-1409', '22-404(A)',
       '14-102(A)', '11-393.70', '22-301(C)', '21-707(D)', '21-1412(A)',
       '76*', '21-902(B1)', '13-401(C)', '71*', '21-1205(B)',
       '21-2091(III)', '16-201(B)', '22-413(D)', '21-405(E1)',
       '16-104.1(D)', '13-936E2V', '51', '21-1105(B)', '22-412.2(D)',
       '17-107', '25-108(C)', '21-1104(C)', '21-1120(B)', '13-401(D)',
       '21-902(C1)', '16-301(J)', '21-1004(E)', '16-301(D)', '55', '79*',
       '16-301(K)', '21-902(A2)', '20-104(C)', '16-302', '67', '68*',
       '11-396.1', '13-401(B)', '83*', '16-114(B)', '72', '73*',
       '22-203(C)', '11-396.17(A)', '54*', '16-112(B)', '21-1120(A)',
       '17-104', '78*', '22-217(A)', '21-902(D1)', '21-904(B2)', '20-106',
       '21-202(H)', '18-106(B)', '21-707(F)', '20-107(D)', '22-412.3(C)',
       '13-936.2(E1)', '14-107(K)', '17-104.1', '13-411', '21-1405(A)',
       '21-311(3)', '22-405.2(A)', '21-904(C1)', '22-412.2(E)',
       '21-209(3)', '21-504(B)', '20-105(C)', '21-309(F)', '16-113(J)',
       '16-105(B2)', '21-1112', '21-802.1', '13-401(E)', '21-1209(D)',
       '21-1104(A)', '20-104(D)', '20-104(B)', '13-616.1(H2)',
       '11-393.10(6B)', '21-401.1', '16-301(G)', '13-702(A)', '13-411(C)',
       '22-213(D)', '21-904(C3)', '21-503(B)', '16-815(C)', '22-223(A)',
       '16-114(D)', '22-402(A)', '13-401(I)', '13-702(B)', '22-403(A)',
       '21-1004(A)', '21-204.1', '12-301(E)', '21-902A(1II)', '7-705(B4)',
       '22-402.1(A)', '13-203(B)', '16-112(E)', '21-1107(B2)',
       '21-707(C)', '21-1003(K)', '70', '18-106(A)', '22-405(D)',
       '16-115(F)', '21-1003(F)', '21-301(B)', '16-303(G)', '21-1107(B1)',
       '21-1306(C)', '13-411(B1)', '21-1126(B)', '21-1114(A)',
       '22-602(A)', '13-415(C)', '21-1412(D)', '11-392.80(A)',
       '16-304(B)', '16-808(A5)', '24-107(B4)', '16-301(F)', '24-106(B)',
       '13-401(F)', '22-227(F)', '21-902(A3)', '21-1004(B)', '13-701(B)',
       '2 1-902(A1I)', '21-1001(C)', '21-204(F)', '17-106(B)',
       '13-620(B)', '21-1209(A1)', '20-104(A)', '13-414(A)', '21-307(D)',
       '16-111.1(F)', '24-106.2(A)', '21-1209(A2)', '21-1003(H)',
       '21-1124(C)', '21-804(C)', '13-403', '22-204(E)', '21-1104(B)',
       '16-105(C)', '21-203(D)', '13-703(H)', '22-217(C)', '22-105(A)',
       '22-402(C)', '55*-', '84*', '24-104.1(M1)', '21-202(L)',
       '22-412(A)', '21-902.1', '26-102(A)', '13-607(B)', '13-625(E)',
       '16-301(L)', '22-230(C)', '21-207(B)', '11-393.60', '13-607(D)',
       '21-507G3I(I1)', '21-1115(A)', '16-301(O)', '26-305(D)',
       '13-936E(2II)', '21-302(B)', '22-218(F)', '11-393.75(A3)',
       '21-707(E)', '21-705(D)', '13-605', '21-1413(A)', '13-940(C)',
       '14-104(B)', '21-1124.3(A)', '21-1207(A)', '21-902(B2I)',
       '16-211(B)', '13-936E(2I)', '11-392.4A', '22-104', '21-1117(B)',
       '21-1111(A)', '21-606(B)', '22-206(B)', '21-1205.1(B3)',
       '21-703(D)', '24-401(C)', '13-411.1(B)', '22-221L2I(II1)',
       '21-1404(B)', '24-101(B)', '11-393.13(0)', '13-703(C)',
       '7-705(B1)', '13-501(A)', '21-1125(3)', '24-107(B1)',
       '22-221(L22)', '69*', '16-303(E)', '21-1205.1(D)', '21-603(B)',
       '21-1111(C)', '15-314(F)', '13-936E2I(I)', '13-401(G)',
       '21-1201(B)', '22-412.2(G)', '21-1205(C)', '21-1105(A)',
       '24-106.1(D1)', '22-214(C)', '22-211(A)', '21-902(C3)',
       '22-105(B)', '21-703.1', '21-303(E)', '21-1210(B)', '21-801(D)',
       '22-219(B)', '23-302(C)', '16-301(I)', '21-1003(V)', '21-1114(D)',
       '21-308(B)', '8-409(H)', '21-1406', '21-1109(B)', '21-1207(D)',
       '22-403(C)', '11-393.83', '22-221L2I(I2)', '26-102(B)',
       '21-1413(B)', '16-808(A6)', '21-801(G)', '13-936E2I(II)',
       '21-205(A)', '21-312(A)', '13-946(C)', '16-808(A3)', '13-704(B)',
       '24-103(B)', '21-313(B)', '21-701(A)', '13-616.1(H1)', '14-107(J)',
       '22-408(C)', '21-904(B3)', '21-703(B)', '21-1205(A)', '14-106(A)',
       '11-383.23', '11-393.75(A1)', '25-202', '21-1210(A)', '21-1116(B)',
       '16-112(C1)', '22-221(C)', '21-10A04A(5)', '24-105(B)',
       '21-1004.1(C)', '22-406(C)', '16-303(I)', '22-419(B2)',
       '22-402(C1)', '21-1123(A2)', '14-110(E)', '21-1101(B)',
       '7-705(B2)', '16-301(N)', '13-936E2I(V)', '11-383.51', '24-103(A)',
       '21-1003(P)', '15-302(A)', '21-606(C)', '16-808(C)', '24-104',
       '11-391.15', '13-502(A)', '24-107(B2)', '22-213(C)',
       '11-396.9C(2)', '22-405(B)', '13-409(A)', '24-106.1(B)',
       '21-1005(F)', '24-105(C1)', '13-415(D)', '21-701(B)', '21-107(C)',
       '21-506(B)', '21-509(A)', '7-705A2(III)', '11-396.3',
       '11-383.91(A)', '14-110(F)', '21-1125(2)', '11-393.13(4)',
       '13-616(I)', '13-921(D2)', '16-810(D)', '22-414', '10-319.2',
       '21-509(C)', '11-391.11(B2)', '13-936.2E(1II)', '11-393.20(1A)',
       '11-390.35', '16-303(A)', '13-708(A)', '22-412.4', '16-104.1(B)',
       '16-104.1(A)', '22-413(A)', '22-412(B)', '24-105(C22)', '13-101.1',
       '62*', '11-393.11(8)', '21-404(E)', '11-396.3(A)', '11-392.33',
       '21-1205.1(A)', '11-393.65', '22-228(A)', '11-396.3A',
       '13-616.2(D2)', '13-420(B)', '11-393.81', '11-393.20(5C)',
       '21-1106(A)', '18-103(C)', '8-409(E)', '22-228(B)', '23-302',
       '11-392.8', '11-385.33(1)', '21-1205.1(C)', '21-511(A3)',
       '21-510(C)', '22-221(E)', '11-393.86', '13-501(E)', '57*',
       '13-620(C)', '13-936.2E(1I)', '21-1125(4)', '25-202(A2)',
       '11-393.30', '13-503(B)', '22-224.1', '11-172.50(0A)',
       '21-902.2(G)', '25-111(D)', '25-112(B3)', '22-408(B)',
       '11-393.45(A)', '13-921(E)', '21-1205.1(B1)', '26-305(D1)',
       '22-217(B)', '22-407(D)', '22-226(B)', '13-415(B)', '21-604(E)',
       '10-303(A)', '15-802', '22-219(D)', '11-393.10(4F)', '21-303(D)',
       '11-393.75(I)', '13-415(E)', '12-301(J)', '24-111.1(B)', '21-1410',
       '11-395.8A', '22-203(D)', '11-393.20(3)', '22-211(D)', '10-306(A)',
       '21-507(A)', '21-1005(D)', '11-396.13', '11-392.10(A)',
       '11-393.75(B)', '22-219(F)', '11-172.20(2A)', '22-219(C)',
       '21-404(D)', '13-402.1(E1)', '13-937.1D(2I)', '22-404(B)',
       '22-215(A)', '22-410(D)', '64*-', '14-110(D)', '21-205(C)',
       '16-301(C)', '10-305(A)', '22-222(B)', '22-221(J)', '21-1132(E5)',
       '23-109(J)', '22-221(B)', '16-112(D)', '22-210(A)', '24-105(C21)',
       '77', '22-602(B)', '24-106(E)', '22-215.1(1)', '21-106(C)',
       '24-109(C)', '16-122(C)', '13-708(B)', '21-1205.1(B)',
       '11-397.17(A)', '13-117(A)', '16-115(H)', '21-1113(C)',
       '16-807(A)', '22-205(B)', '21-1207(B)', '11-393.75(H1)',
       '22-408(A)', '22-404.1(B)', '22-213(E)', '11-172.51(6)',
       '22-210(D)', '21-1131(A)', '22-414.1', '11-393.80', '21-806(B)',
       '22-412(F)', '22-404.3(A)', '65*-', '90', '61*-', '52', '66*',
       '61-', '71*-', '82*', '14-105(E)', '20-102(B2)', '11-395.15(G)',
       '21-1412(C)', '21-1207(A1)', '22-206(A2)', '21-(B)', '22-(I1)',
       '13-', '21-(D2)', '13-(A)', '21-310(B)', '22-228(D)', '16-101(A2)',
       '11-395.3A(1)', '13-403(A1)', '11-393.23', '21-1132(D1)',
       '21-1205.1(B2)', '22-222(A2)', '22-222(A1)', '11-393.17(A)',
       '21-901.2(A)', '21-510(A)'], dtype=object)

In [51]:
df['Search Reason For Stop'].nunique()

836

                                                            Search Type

In [52]:
#Check the number of unique values
df['Search Type'].nunique()

6

In [53]:
#Check the unique values
df['Search Type'].value_counts()

Search Type
Both                 66857
Property             11946
Person               10420
car                      4
Search Incidental        3
PC                       3
Name: count, dtype: int64

In [54]:
#Check for null values
df['Search Type'].isnull().sum()

np.int64(1978528)

In [55]:
#Fill the null values
df['Search Type']=df['Search Type'].fillna("Not applicable")

In [56]:
#Check for null values
df['Search Type'].isnull().sum()

np.int64(0)

In [57]:
#Check the unique values
df['Search Type'].value_counts()

Search Type
Not applicable       1978528
Both                   66857
Property               11946
Person                 10420
car                        4
Search Incidental          3
PC                         3
Name: count, dtype: int64

                                                Search Arrest Reason

In [58]:
#Check for unique values
df['Search Arrest Reason'].value_counts()

Search Arrest Reason
Stop         39896
Search       11679
Other         6900
Warrant       3176
Traffic         28
DUI             13
alcohol          6
Marihuana        5
Criminal         3
driving          3
DWI              2
Name: count, dtype: int64

In [59]:
df['Search Arrest Reason'].isnull().sum()

np.int64(2006050)

In [60]:
df['Search Arrest Reason']=df['Search Arrest Reason'].fillna("Not applicable")

In [61]:
df['Search Arrest Reason'].isnull().sum()

np.int64(0)

In [62]:
df['Search Arrest Reason'].value_counts()

Search Arrest Reason
Not applicable    2006050
Stop                39896
Search              11679
Other                6900
Warrant              3176
Traffic                28
DUI                    13
alcohol                 6
Marihuana               5
Criminal                3
driving                 3
DWI                     2
Name: count, dtype: int64

                                                       STATE

In [63]:
df['State'].value_counts()

State
MD    1795997
VA      98165
DC      50874
XX      16419
PA      14284
       ...
NF          2
AS          2
MH          2
NU          1
IT          1
Name: count, Length: 72, dtype: int64

In [64]:
df['State'].nunique()

72

In [65]:
import us  

def normalize_state(code):
    if code is None:
        return None
    code = str(code).strip().upper()
    # Keep valid US states or DC
    if us.states.lookup(code) or code == "DC":
        return code
    else:
        return "NON-US"

# Apply to your DataFrame
df['State'] = df['State'].apply(normalize_state)

In [66]:
# Collapse counts
df['State'].value_counts()

State
MD        1795997
VA          98165
DC          50874
NON-US      17788
PA          14284
TX          10106
FL          10023
WV           8282
NC           7518
NY           6521
NJ           5871
GA           4447
DE           3832
CA           3511
OH           3195
MA           2690
IL           2182
SC           2123
TN           1939
MI           1638
AZ           1580
IN           1472
CT           1361
AL           1116
KY            758
MO            740
OK            728
WA            723
CO            694
WI            687
LA            667
MS            633
ME            587
MN            574
RI            364
AR            361
UT            358
NM            341
NV            338
NH            330
IA            313
OR            307
VT            275
KS            270
AK            221
ND            196
ID            169
MT            159
SD            123
NE            109
HI             96
WY             56
VI             38
GU             16
PR             13
AS              2
Name: count, dtype: int64

In [67]:
df['State'].nunique()

56

In [68]:
df['State'].isnull().sum()

np.int64(0)

                                                   Vehicle Type

In [69]:
df['VehicleType'].value_counts()

VehicleType
02 - Automobile              1833630
05 - Light Duty Truck         108173
28 - Other                     35055
03 - Station Wagon             28614
01 - Motorcycle                19052
06 - Heavy Duty Truck          16426
29 - Unknown                   11153
08 - Recreational Vehicle       5502
19 - Moped                      2308
25 - Utility Trailer            1965
07 - Truck/Road Tractor         1816
20 - Commercial Rig             1144
04 - Limousine                   959
10 - Transit Bus                 685
12 - School Bus                  432
27 - Farm Equipment              135
29 - Other                       116
09 - Farm Vehicle                108
26 - Boat Trailer                101
21 - Tandem Trailer               88
11 - Cross Country Bus            66
23 - Travel/Home Trailer          34
30 - Unknown                      30
22 - Mobile Home                  27
28 - Electric Bicycle             27
24 - Camper                       26
18 - Police(Non-Emerg)            22
14 - Ambulance(Non-Emerg)         20
13 - Ambulance(Emerg)             14
15 - Fire(Emerg)                  13
16 - Fire(Non-Emerg)               5
17 - Police(Emerg)                 5
18 - Police Vehicle                4
15 - Fire Vehicle                  3
14 - Ambulance                     2
13 - Ambulance                     1
Name: count, dtype: int64

In [70]:
df['VehicleType'].nunique()

36

In [71]:
# Create a new column VehicleType_clean by cleaning the original

def vehicle_split(text):

 return text.split("-",1)[1].strip()

df['VehicleType_clean']=df['VehicleType'].apply(vehicle_split)

In [72]:
df['VehicleType_clean'].nunique()

33

                                                              YEAR

In [73]:
df['Year'].value_counts()

Year
2007.0    111399
2013.0    110226
2006.0    110102
2012.0    108133
2005.0    105819
           ...
1478.0         1
5657.0         1
8747.0         1
3564.0         1
1201.0         1
Name: count, Length: 429, dtype: int64

In [74]:

import pandas as pd

# Convert to integer type (nullable)
df['Year_clean'] = df['Year'].astype('Int64')

# Replace impossible years with NA
df.loc[(df['Year_clean'] < 1960) | (df['Year_clean'] > 2025), 'Year_clean'] = pd.NA

# Check for nulls
null_count = df['Year_clean'].isnull().sum()
print("Null values in Year_clean:", null_count)

Null values in Year_clean: 13697

In [75]:
df['Year_clean']

0          2007
1          2005
2          2005
3          2005
4          2005
           ...
2070110    2011
2070111    2020
2070112    2010
2070113    2019
2070114    2019
Name: Year_clean, Length: 2067761, dtype: Int64

                                                         MAKE

In [76]:
df['Make'].value_counts()

Make
TOYOTA      240246
HONDA       226701
FORD        187504
TOYT        116706
NISSAN      109327
             ...
SYMG             1
TESULA           1
ALFA ROM         1
BMWQ             1
OTA              1
Name: count, Length: 4935, dtype: int64

In [77]:
import pandas as pd

# Normalize first
df['Make_clean'] = df['Make'].str.strip().str.upper()

# Define mapping dictionary
mapping = {
    r'^TOY.*': 'TOYOTA',          # TOY, TOYT, TOYYOT  → TOYOTA
    r'^BMW.*': 'BMW',             # BMWQ → BMW
    r'FRIEGHT': 'FREIGHTLINER',   # FRIEGHT → FREIGHTLINER
    r'FORSCHE': 'PORSCHE',        # FORSCHE → PORSCHE
    r"^CHEV.*" :  'CHEVROLET' ,   #CHEV,CHEVY ->CHEVROLET 
    r"^HYUN.*": "HYUNDAI",        #HYUND,HYUN ->HYUNDAI
    r"^NISS.*":"NISSAN",          #NISS,NISSIAN ->NISSAN
    r"^HON.*":"HONDA",            #HOND,HONDA ->HONDA
    r"^MER.*":"MERCEDES",         #MERZ,MERCEDES->MERCEDES
    r"^VOLK.*":"VOLKSWAGON",      #VOLK ->VOLKSWAGON
    r"^VK$":"VOLKSWAGON",         #VK->VOLKSWAGON
    r"^CHRY.*":"CHRYSLER",        #CHRY ->CHRYSLER
    r"^MAZD.*":"MAZDA",           #MAZD ->MAZDA
    r"^INFI.*":"INFINITY",        #INFI ->INFINITY
    r"^LEX.*":"LEXUS",            #LEX ->LEXUS
    r"^VOLV.*":"VOLVO",           #VOLV->VOLVO
    r"^PONT.*":"PONTIAC",         #PONT ->PONTIAC
    r"^LINC.*":"LINCOLN",         # LINC->LINCOLN
    r"^BUIC.*":"BUICK",           #BUIC ->BUICK
    r"^MERC.*":"MERCEDES",        #MERC->MERCEDES
    r"^TESL.*":"TESLA",           #TESL->TESLA
    r"^JAGU.*":"JAGUAR",          #JAGU->JAGUAR
    r"^SUZ.*":"SUZUKI",           #SUZU,SUZI->SUZUKI            
    r"^MITSU.*":"MITSUBISHI",     #MITSU -> MITSUBISHI
    r"^YAMA.*":"YAMAHA",          #YAMA -> YAMAHA
    r"^MADZA.*":"MAZDA"         #YAMA -> YAMAHA



}

# Apply replacements using regex
df['Make_clean'] = df['Make_clean'].replace(mapping, regex=True)

In [78]:
df['Make_clean'].value_counts()
#4935 count reduced to 3809 in MAKE COLUMN

Make_clean
TOYOTA       367140
HONDA        307985
FORD         187504
NISSAN       155619
CHEVROLET    151213
              ...
POSCHE            1
CADALIAC          1
OTA               1
AUBARU            1
KUA               1
Name: count, Length: 3809, dtype: int64

                                                  MODEL

In [79]:
df['Model'].isnull().sum()

np.int64(223)

In [80]:
df['Model'].value_counts()

Model
4S          199553
TK          123839
CIVIC        76370
ACCORD       75248
CAMRY        71373
             ...
AMG EQS          1
TFX              1
NS               1
X-7              1
OUTLINER         1
Name: count, Length: 23386, dtype: int64

In [81]:
#Normalize Case
df['Model_clean'] = df['Model'].str.strip().str.upper()

#Regex-Based Fixes for Common Variants
mapping = {
    r'^CAMRY.*': 'CAMRY',          # CAMERY LE → CAMRY
    r'^CIVIC.*': 'CIVIC',          # CIVIC LX, CIVIC EX → CIVIC
    r'^ACCORD.*': 'ACCORD',        # ACCORD EX → ACCORD
    r'^4S.*': '4 SERIES',          # BMW 4S → BMW 4 SERIES
    r'^TK.*': 'TRUCK',             # TK, TK P/U → TRUCK
    r'TONDRA': 'TUNDRA',           # typo fix
    r'CONVE': 'CONVERTIBLE',       # abbreviation
    r'LIMITES SUV': 'LIMITED SUV'  # typo fix
}

df['Model_clean'] = df['Model_clean'].replace(mapping, regex=True)

#Remove Cryptic Abbreviations
df['Model_clean'] = df['Model_clean'].str.replace(r'\b(LE|LX|EX|SUV|P/U)\b', '', regex=True).str.strip()
df['Model_clean'] = df['Model_clean'].replace('', pd.NA)


print(df['Model_clean'].value_counts().head(10))

Model_clean
4 SERIES    205955
TRUCK       137536
CIVIC        78993
ACCORD       77414
CAMRY        73406
COROLLA      62471
ALTIMA       39278
4D           32465
2S           28800
4DR          25775
Name: count, dtype: int64

In [82]:
print(df['Model_clean'].value_counts())
print("The Null count is ")
df['Model'].isnull().sum()

Model_clean
4 SERIES    205955
TRUCK       137536
CIVIC        78993
ACCORD       77414
CAMRY        73406
             ...
SW-FOCUS         1
SCRUZ            1
MAIL VAN         1
FOCUS/4D         1
GLC30            1
Name: count, Length: 20860, dtype: int64
The Null count is

np.int64(223)

                                                             COLOUR

In [83]:
df['Color'].isnull().sum()

np.int64(22265)

In [84]:
df['Color'].value_counts()

Color
BLACK          436741
SILVER         365410
WHITE          341530
GRAY           252862
RED            157087
BLUE           150538
GREEN           62565
GOLD            56015
BLUE, DARK      44000
TAN             35616
MAROON          34111
BLUE, LIGHT     24715
BEIGE           20267
GREEN, DK       18659
GREEN, LGT      10155
BROWN            8731
ORANGE           7336
YELLOW           7231
BRONZE           4503
PURPLE           3759
MULTICOLOR       1560
CREAM            1115
COPPER            590
PINK              315
CHROME             45
CAMOUFLAGE         40
Name: count, dtype: int64

In [85]:
df['Color'].nunique()

26

In [86]:
import pandas as pd

# Normalize case
df['Color_clean'] = df['Color'].str.strip().str.upper().fillna("")

# Define fixed palette mapping
color_map = {
    r'^BLACK.*': 'BLACK',
    r'^WHITE.*': 'WHITE',
    r'^SILVER.*': 'SILVER',
    r'^GRAY.*': 'GRAY',
    r'^RED.*': 'RED',
    r'^BLUE.*': 'BLUE',
    r'^GREEN.*': 'GREEN',
    r'^GOLD.*': 'GOLD',
    r'^BEIGE.*': 'BEIGE',
    r'^TAN.*': 'BEIGE',
    r'^CREAM.*': 'BEIGE',
    r'^MAROON.*': 'RED',
    r'^ORANGE.*': 'ORANGE',
    r'^YELLOW.*': 'YELLOW',
    r'^BROWN.*': 'BROWN',
    r'^BRONZE.*': 'BROWN',
    r'^COPPER.*': 'BROWN',
    r'^PURPLE.*': 'PURPLE',
    r'^PINK.*': 'PINK',
    r'^CHROME.*': 'SILVER',
    r'^CAMOUFLAGE.*': 'MULTICOLOR',
    r'^MULTICOLOR.*': 'MULTICOLOR',
    # Abbreviations
    r'BLUE, DARK': 'BLUE',
    r'BLUE, LIGHT': 'BLUE',
    r'GREEN, DK': 'GREEN',
    r'GREEN, LGT': 'GREEN'
}

# Apply mapping
df['Color_clean'] = df['Color_clean'].replace(color_map, regex=True)

# Collapse anything outside the palette into OTHER
standard_colors = [
    'BLACK','WHITE','SILVER','GRAY','RED','BLUE','GREEN',
    'GOLD','BEIGE','BROWN','ORANGE','YELLOW','PURPLE','PINK','MULTICOLOR'
]
df['Color_clean'] = df['Color_clean'].where(df['Color_clean'].isin(standard_colors), 'OTHER')

In [87]:
df['Color_clean'].nunique()
#26 colours reduced to 16 now

16

In [88]:
df['Color_clean'].isnull().sum()

np.int64(0)

                                                VIOLATION TYPE

In [89]:
df['Violation Type'].value_counts()

Violation Type
Warning     1089807
Citation     885280
ESERO         91778
SERO            896
Name: count, dtype: int64

In [90]:
df['Violation Type'].isnull().sum()

np.int64(0)

In [91]:
df['Violation Type']=df['Violation Type'].str.strip()

                                                        Charge

In [92]:
df['Charge'].value_counts()

Charge
21-801.1      286697
21-201(a1)    171274
13-409(b)      91428
21-707(a)      65528
13-401(h)      61493
               ...
22-303             1
16-815(e)          1
13-113(e3)         1
11-395.8           1
22-402(c3)         1
Name: count, Length: 1199, dtype: int64

In [93]:
df['Charge'].nunique()

1199

In [94]:
df['Charge'].isnull().sum()

np.int64(0)

In [95]:
df.groupby('SeqID').size()

SeqID
00001e27-8bde-4328-8b33-2d2d9a9ce862    1
0000395c-bbf9-49e3-ba75-91e2da9e98d7    2
00006268-72eb-42ff-b6b0-50c21d820e9c    1
000071c5-c385-4191-9cd7-e854d2054963    1
000099b1-4dcb-4f94-8aef-71ffb198890b    2
                                       ..
ffffb408-d39e-4c3e-a573-90328763c50c    1
ffffbf8d-668b-49fd-b51d-fe5e5421ae49    1
ffffde34-c896-4614-a480-73600e8500a1    1
fffff356-9830-4664-a240-3f34341c7efc    1
fffff914-df6f-4634-97d3-e2202f3d1f86    1
Length: 1178080, dtype: int64

In [96]:
df['Charge']=df['Charge'].str.strip().str.upper()

In [97]:
df['Charge'].value_counts()

Charge
21-801.1        286697
21-201(A1)      171274
13-409(B)        91428
21-707(A)        65528
13-401(H)        61493
                 ...
11-395.3A(2)         1
11-395.8             1
21-1132(D1)          1
13-626(F)            1
11-395.15(G)         1
Name: count, Length: 1192, dtype: int64

In [98]:
#Handle Multiple Charges per Stop
charges_per_seqid = df.groupby('SeqID')['Charge'].apply(list).reset_index()
charges_per_seqid.head()

                                  SeqID                      Charge
0  00001e27-8bde-4328-8b33-2d2d9a9ce862                 [21-503(C)]
1  0000395c-bbf9-49e3-ba75-91e2da9e98d7  [21-201(A1), 11-393.95(F)]
2  00006268-72eb-42ff-b6b0-50c21d820e9c                 [22-226(A)]
3  000071c5-c385-4191-9cd7-e854d2054963                [21-201(A1)]
4  000099b1-4dcb-4f94-8aef-71ffb198890b      [21-801(B), 21-801(A)]

                                                    Article

In [99]:
df['Article'].value_counts()

Article
Transportation Article    1955103
Maryland Rules              19889
BR                             61
TG                             22
1A                              9
00                              3
Name: count, dtype: int64

In [100]:
df['Article'].isnull().sum()

np.int64(92674)

In [101]:
# Normalize Text
df['Article_clean'] = df['Article'].str.strip().str.upper()

# Standardize Known Variants
article_map = {
    r'^BR$': 'BUSINESS REGULATION ARTICLE',
    r'^TG$': 'TAX-GENERAL ARTICLE',
    r'^1A$': 'ARTICLE 1A',
    r'^00$': 'UNKNOWN'
}
df['Article_clean'] = df['Article_clean'].replace(article_map, regex=True)

# Replace NaN with empty string before group fill
df['Article_clean'] = df['Article_clean'].fillna('')

# Fill Missing Values by Group (SeqID)
df['Article_clean'] = df.groupby('SeqID')['Article_clean'].transform(
    lambda x: x.replace('', x.mode()[0] if not x.mode().empty else '')
)

In [102]:
print(df['Article_clean'].value_counts())

Article_clean
TRANSPORTATION ARTICLE         1972148
                                 75034
MARYLAND RULES                   20484
BUSINESS REGULATION ARTICLE         61
TAX-GENERAL ARTICLE                 22
ARTICLE 1A                           9
UNKNOWN                              3
Name: count, dtype: int64

In [103]:
df['Article_clean'].isnull().sum()

np.int64(0)

                                        Contributed To Accident

In [104]:
df['Contributed To Accident'].value_counts()

Contributed To Accident
False    2011283
True       56478
Name: count, dtype: int64

In [105]:
#Double confirm the data tuype and the unique values
print(df['Contributed To Accident'].dtype)
print(df['Contributed To Accident'].unique())

#So there is no need to clean this column data

bool
[False  True]

                                             Race

In [106]:
df['Race'].value_counts()

Race
WHITE              690418
BLACK              655425
HISPANIC           463921
OTHER              137829
ASIAN              116652
NATIVE AMERICAN      3516
Name: count, dtype: int64

In [107]:
df['Race'].isnull().sum()

np.int64(0)

In [108]:
df['Race'].nunique()

6

            There are no null values in this column RACE.So need not clean the data in RACE

                                   Gender

In [109]:
df['Gender'].value_counts()

Gender
M    1392231
F     672009
U       3521
Name: count, dtype: int64

In [110]:
df['Gender'].nunique()

3

In [111]:
df['Gender'].isnull().sum()

np.int64(0)

In [112]:
df['Gender_clean']=df['Gender'].replace('U','Unknown',regex=False)

In [113]:
df['Gender_clean'].value_counts()

Gender_clean
M          1392231
F           672009
Unknown       3521
Name: count, dtype: int64

                                            Driver City

In [114]:
df['Driver City'].value_counts()

Driver City
SILVER SPRING    502406
GAITHERSBURG     221037
GERMANTOWN       179096
ROCKVILLE        167635
WASHINGTON        65124
                  ...
SNOQUALMIE            1
INDIAATLANTIC         1
SODDY DAISY           1
QWINGS MILLS          1
TAKKOMA PARK          1
Name: count, Length: 9374, dtype: int64

In [115]:
df['Driver City'].isnull().sum()

np.int64(514)

In [116]:
# Step 1: Normalize case and whitespace
df['Driver City'] = df['Driver City'].str.strip().str.upper()

# Step 2: Fix known typos with dictionary (vectorized replace)
city_map = {
    "TAKKOMA PARK": "TAKOMA PARK",
    "QWINGS MILLS": "OWINGS MILLS",
    "WESTIMINISTER": "WESTMINSTER"
}
df['Driver City'] = df['Driver City'].replace(city_map)

# Step 3: Handle nulls directly
df['Driver City'] = df['Driver City'].fillna("UNKNOWN")

In [117]:
print(df['Driver City'].value_counts())

Driver City
SILVER SPRING    502406
GAITHERSBURG     221037
GERMANTOWN       179096
ROCKVILLE        167635
WASHINGTON        65124
                  ...
ELK RIVER             1
VAILSBURG             1
HYATTSVILLY           1
EDWARDSVILLE          1
WARETOWN              1
Name: count, Length: 9371, dtype: int64

In [118]:
df['Driver City'].isnull().sum()

np.int64(0)

                                             Driver State

In [119]:
df['Driver State'].value_counts()

Driver State
MD    1869718
DC      67710
VA      62798
PA      10181
FL       7221
       ...
SK          4
NS          3
PE          2
PQ          1
IT          1
Name: count, Length: 68, dtype: int64

In [120]:
import us  

def normalize_state(code):
    if code is None:
        return None
    code = str(code).strip().upper()
    # Keep valid US states or DC
    if us.states.lookup(code) or code == "DC":
        return code
    else:
        return "NON-US"

# Apply to your DataFrame
df['State'] = df['State'].apply(normalize_state)

In [121]:
df['Driver State'].isnull().sum()

np.int64(11)

In [122]:
df['Driver State'].value_counts()

Driver State
MD    1869718
DC      67710
VA      62798
PA      10181
FL       7221
       ...
SK          4
NS          3
PE          2
PQ          1
IT          1
Name: count, Length: 68, dtype: int64

In [123]:
df[df['Driver State']=="NON-US"]

Empty DataFrame
Columns: [SeqID, Date Of Stop, Time Of Stop, Agency, SubAgency, Description, Location, Latitude, Longitude, Accident, Belts, Personal Injury, Property Damage, Fatal, Commercial License, HAZMAT, Commercial Vehicle, Alcohol, Work Zone, Search Conducted, Search Disposition, Search Outcome, Search Reason, Search Reason For Stop, Search Type, Search Arrest Reason, State, VehicleType, Year, Make, Model, Color, Violation Type, Charge, Article, Contributed To Accident, Race, Gender, Driver City, Driver State, DL State, Arrest Type, Geolocation, stop_timestamp, District_number, Violation_Category, Location_clean, Roads, VehicleType_clean, Year_clean, Make_clean, Model_clean, Color_clean, Article_clean, Gender_clean]
Index: []

[0 rows x 55 columns]

So it is obvious that the Driver State column has no NON US data values in it

                                            DL State()

In [124]:
df['DL State'].value_counts()

DL State
MD    1803488
DC      68711
VA      66775
XX      29575
PA      12051
       ...
YT          7
PQ          6
MH          5
NU          3
NF          2
Name: count, Length: 72, dtype: int64

In [125]:
df['DL State'].isnull().sum()

np.int64(929)

In [126]:
import us  

def normalize_state(code):
    if code is None:
        return None
    code = str(code).strip().upper()
    # Keep valid US states or DC
    if us.states.lookup(code) or code == "DC":
        return code
    else:
        return "NON-US"

# Apply to your DataFrame
df['State'] = df['State'].apply(normalize_state)

In [127]:
df[df['DL State']=="NON-US"]

Empty DataFrame
Columns: [SeqID, Date Of Stop, Time Of Stop, Agency, SubAgency, Description, Location, Latitude, Longitude, Accident, Belts, Personal Injury, Property Damage, Fatal, Commercial License, HAZMAT, Commercial Vehicle, Alcohol, Work Zone, Search Conducted, Search Disposition, Search Outcome, Search Reason, Search Reason For Stop, Search Type, Search Arrest Reason, State, VehicleType, Year, Make, Model, Color, Violation Type, Charge, Article, Contributed To Accident, Race, Gender, Driver City, Driver State, DL State, Arrest Type, Geolocation, stop_timestamp, District_number, Violation_Category, Location_clean, Roads, VehicleType_clean, Year_clean, Make_clean, Model_clean, Color_clean, Article_clean, Gender_clean]
Index: []

[0 rows x 55 columns]

So it is obvious that the DL State column has no NON US data values in it

                                           Arrest Type

In [128]:
df['Arrest Type'].value_counts()

Arrest Type
A - Marked Patrol                         1655405
Q - Marked Laser                           199196
B - Unmarked Patrol                         97603
L - Motorcycle                              20953
G - Marked Moving Radar (Stationary)        19823
S - License Plate Recognition               16395
E - Marked Stationary Radar                 16124
O - Foot Patrol                             14898
R - Unmarked Laser                          11159
M - Marked (Off-Duty)                        5519
I - Marked Moving Radar (Moving)             4298
H - Unmarked Moving Radar (Stationary)       2660
F - Unmarked Stationary Radar                1065
J - Unmarked Moving Radar (Moving)           1055
C - Marked VASCAR                             543
P - Mounted Patrol                            365
N - Unmarked (Off-Duty)                       326
D - Unmarked VASCAR                           317
K - Aircraft Assist                            57
Name: count, dtype: int64

In [129]:
df['Arrest Type'].nunique()

19

                                                   Geolocation

In [130]:
df['Geolocation'].isnull().sum()

np.int64(0)

In [131]:
df['Geolocation'].head(10)

0                               (0.0, 0.0)
1                   (39.097965, -77.15301)
2                   (39.097965, -77.15301)
3                   (39.097965, -77.15301)
4                   (39.097965, -77.15301)
5    (39.0530383333333, -77.0246366666667)
6                   (39.097965, -77.15301)
7                   (39.097965, -77.15301)
8                   (39.097965, -77.15301)
9                   (39.097965, -77.15301)
Name: Geolocation, dtype: object

In [132]:
import numpy as np

# 1. Split into Latitude_geo and Longitude
df[["Latitude_geo", "Longitude_geo"]] = (
    df["Geolocation"]
    .str.strip("()")              # remove parentheses
    .str.split(",", expand=True)  # split into two parts
)

# 2. Convert to float
df["Latitude_geo"] = df["Latitude_geo"].astype(float)
df["Longitude_geo"] = df["Longitude_geo"].astype(float)

# 3. Replace invalid (0.0, 0.0) with NaN
df.loc[(df["Latitude_geo"] == 0.0) & (df["Longitude_geo"] == 0.0), ["Latitude_geo", "Longitude_geo"]] = np.nan

In [133]:
df[["Latitude_geo", "Longitude_geo"]].head()

   Latitude_geo  Longitude_geo
0           NaN            NaN
1     39.097965      -77.15301
2     39.097965      -77.15301
3     39.097965      -77.15301
4     39.097965      -77.15301

In [134]:
# Compare Latitude_geo with existing Latitude column
if "Latitude" in df.columns:
    lat_match = (df["Latitude_geo"].round(6) == df["Latitude"].round(6))
    print("Latitude_geo matches Latitude in", lat_match.sum(), "rows out of", len(df))

# Compare Longitude with existing Longitude column
if "Longitude" in df.columns:
    lon_match = (df["Longitude_geo"].round(6) == df["Longitude"].round(6))
    print("Longitude_geo matches Longitude in", lon_match.sum(), "rows out of", len(df))

Latitude_geo matches Latitude in 1912005 rows out of 2067761
Longitude_geo matches Longitude in 1912007 rows out of 2067761

Looking at these statistics,it is better to go with Latitude and Longitude columns instead of Latitude_geo and Longitude_geo

In [135]:
df.to_csv("Traffic_Violations_cleaned.csv")

In [136]:
def create_connection():
    
    import mysql.connector
    from mysql.connector import Error
    try:
        connection = mysql.connector.connect(
            host="localhost",
            user="root",
            password="root",
            database="traffic"
        )
        if connection.is_connected():
            print("Successfully connected to MySQL")
            return connection
    except Error as err:
        print(f"Error: {err}")
        return None

In [137]:
conn=create_connection()
print(conn)

Successfully connected to MySQL
<mysql.connector.connection_cext.CMySQLConnection object at 0x000001ECED653CA0>

In [138]:
from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://root:root@localhost/traffic")

In [139]:
df['Roads'] = df['Roads'].apply(
    lambda x: ', '.join(map(str, x)) if isinstance(x, list) else str(x)
)

In [140]:
with engine.begin() as conn:
    df.to_sql(
        name="traffic_violations_cleaned",
        con=conn,          # <-- use conn here
        if_exists="replace",
        index=False,
        chunksize=1000     # optional, avoids packet size issues
    )

In [ ]:
"""
   accidents_per_loc = (
     traffic_df.groupby(["Location", "Latitude", "Longitude"])["Accident"]
      .apply(lambda x: np.sum(x == True))
      .reset_index(name="Accident_Count")
      .sort_values("Accident_Count", ascending=False)
   ) 
   print("Accidents per Location",accidents_per_loc)
   
   st.info("High Risk Zones :" )
   st.dataframe(accidents_per_loc.head(50))    
   """

In [ ]:

"""
def select_highest_traffic_incident(traffic_df):
     incident_count_df=traffic_df.groupby(["Location_clean","Latitude","Longitude"]).size().reset_index(name="incident_count").sort_values("incident_count",ascending=False)
     max_incident_row_df=incident_count_df.loc[incident_count_df["incident_count"].idxmax()]
     return max_incident_row_df,incident_count_df
   """